# Generated by Django 5.1.7 on 2025-08-27 17:47

import aluno.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(default=aluno.models.gerar_matricula, editable=False, max_length=20, unique=True),
        ),
    ]
