# Generated by Django 5.1.7 on 2025-09-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='m_apoio',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Material de Apoio'),
        ),
    ]
