# Generated by Django 5.1.6 on 2025-08-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='curriculo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='formacao',
            field=models.CharField(max_length=255),
        ),
    ]
