# Generated by Django 5.1.7 on 2025-09-02 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_mat', models.DateField(verbose_name='Data de Matrícula')),
                ('status', models.CharField(choices=[('matriculado', 'Matriculado'), ('cursando', 'Cursando'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('suspenso', 'Suspenso')], default='matriculado', max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'unique_together': {('aluno', 'curso')},
            },
        ),
    ]
